[package]
name = "libcubiomes-sys"
version = "0.1.0"
edition = "2021"
authors = [ "EnderKill98 " ]

build = "build/build.rs"
links = "cubiomes"

[build-dependencies]
anyhow = "1"
bindgen = "0.60"
cc = "1"
fs_extra = "1"
